apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-astro-template
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: "{{{ image }}}"
  port: 3000
  liveness:
    path: /api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /api/internal/isReady
    initialDelay: 10
  replicas:
    min: 1
    max: 2
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  accessPolicy:
    inbound:
      rules:
        - application: sokos-utbetalingsportalen
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: "20m"
      memory: 128Mi
  env:
    - name: SOKOS_SKATTEKORT_PERSON_API
      value: "https://sokos-skattekort-person"
