name: Dependabot Auto-merge

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "LICENCE"
      - "CODEOWNERS"
      - ".gitignore"
      - ".github/workflows/build-pr.yaml"
      - ".github/workflows/deploy.yaml"
      - ".github/workflows/manual-deploy-dev.yaml"
      - ".github/workflows/playwright.yaml"
      - ".github/workflows/security.yaml"
      - ".github/dependabot.yaml"

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  dependabot-automerge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Automerge Dependabot PRs
        uses: navikt/automerge-dependabot@main
        with:
          token: ${{ github.token }}
          auto-approve: 'true'
          merge-method: 'squash'
          semver-filter: 'patch,minor'
          minimum-age-of-pr: '0'