name: Deploy application

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "LICENCE"
      - "CODEOWNERS"
      - ".gitignore"
      - ".github/workflows/build-pr.yaml"
      - ".github/workflows/dependabot-automerge.yaml"
      - ".github/workflows/manual-deploy.yaml"
      - ".github/workflows/playwright.yaml"
      - ".github/workflows/security.yaml"
      - ".github/dependabot.yaml"

env:
  TZ: Europe/Oslo

permissions:
  contents: write
  id-token: write
  pull-requests: write
  deployments: write

jobs:
  build:
    name: Build/test & push image
    uses: navikt/mob-gha-workflows/.github/workflows/node-build-push-image-v2.yaml@main
    secrets: inherit

  deploy-dev:
    needs: build
    name: Deploy to dev
    uses: navikt/mob-gha-workflows/.github/workflows/nais-deploy.yaml@main
    with:
      cluster: dev-gcp
      resource: .nais/naiserator-dev.yaml
      image: ${{ needs.build.outputs.image }}

  # deploy-prod:
  #   needs: [build, deploy-dev]
  #   name: Deploy to prod
  #   uses: navikt/mob-gha-workflows/.github/workflows/nais-deploy.yaml@main
  #   with:
  #     cluster: prod-gcp
  #     resource: .nais/naiserator-prod.yaml
  #     image: ${{ needs.build.outputs.image }}
