name: Deploy application manually

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: choice
        options:
          - dev
          - prod

env:
  TZ: Europe/Oslo

jobs:
  build-push-image:
    permissions:
      contents: read
      id-token: write
    name: Build application & build/push image
    uses: navikt/mob-gha-workflows/.github/workflows/node-build-push-image-v2.yaml@main
    secrets: inherit

  deploy-dev:
    permissions:
      contents: read
      id-token: write
      pull-requests: write
      deployments: write
    needs: [build-push-image]
    name: ${{ inputs.environment == 'prod' && 'Deploy to prod-gcp' || 'Deploy to dev-gcp' }}
    uses: navikt/mob-gha-workflows/.github/workflows/nais-deploy.yaml@main
    with:
      cluster: ${{ inputs.environment == 'prod' && 'prod-gcp' || 'dev-gcp' }}
      resource: .nais/naiserator-${{ inputs.environment }}.yaml
      image: ${{ needs.build-push-image.outputs.image }}
